#:import hex kivy.utils.get_color_from_hex
WindowManager:
    LoginScreen:
    AddTaskScreen:
    ViewTaskScreen:
    ListViewScreen:


<LoginScreen>:
    name: "login"
    on_pre_leave: root.manager.update_current_user(root.current_user)
    canvas.before:
        Rectangle:
            size: self.size
            source: "resources/images/5039684.jpg"
    GridLayout:
        cols: 3

        BoxLayout:
            size_hint: .05, 1

        StackLayout:
            pos_hint: {"center_x" : .5, "center_y" : 1}

            RelativeLayout:
                Label:
                    id: Title
                    pos_hint: {"center_x": .507, "center_y": .882}
                    size_hint: .6, .35
                    font_size: dp(98)
                    font_name: "resources/fonts/Prototype.ttf"
                    color: hex("#df4da3")
                    text: "Task.r"
                Label:
                    id: Title
                    pos_hint: {"center_x": .5, "center_y": .875}
                    size_hint: .6, .35
                    font_size: dp(98)
                    font_name: "resources/fonts/Prototype.ttf"
                    color: hex("#4da3df")
                    text: "Task.r"
                Label:
                    id: header
                    pos_hint: {"center_x": .5, "center_y": .725}
                    size_hint: .6, .1
                    font_size: dp(50)
                    text: root.header_text
                    color: hex("#b8daf2")
                    font_name: "resources/fonts/Prototype.ttf"
                Label:
                    id: user_name_label
                    pos_hint: {"center_x" : .25, "center_y" : .6}
                    size_hint: .6, .0525
                    text: "Username"
                    font_name: "resources/fonts/Prototype.ttf"
                    font_size: dp(20)

                Label:
                    id: invalid_name_label
                    pos_hint: {"center_x" : .75, "center_y" : .6}
                    size_hint: .6, .0525
                    text: "Invalid Entry!"
                    color: "red"
                    opacity: 0
                    font_name: "resources/fonts/Prototype.ttf"
                    font_size: dp(20)

                TextInput:
                    id: username
                    pos_hint: {"center_x" : .5, "center_y" : .55}
                    size_hint: .75, .055
                    text: root.username_input
                    multiline: False
                    write_tab: False
                    on_focus: root.clear_username()
                    text_validate_unfocus: False
                    on_text_validate: root.username_input = username.text

                Label:
                    id: user_password_label
                    pos_hint: {"center_x" : .25, "center_y" : .425}
                    size_hint: .6, .0525
                    text: "Password"
                    font_name: "resources/fonts/Prototype.ttf"
                    font_size: dp(20)

                Label:
                    id: invalid_password_label
                    pos_hint: {"center_x" : .75, "center_y" : .425}
                    size_hint: .6, .0525
                    opacity: 0
                    text: "Invalid Entry!"
                    color: "red"
                    font_name: "resources/fonts/Prototype.ttf"
                    font_size: dp(20)

                TextInput:
                    id: password
                    pos_hint: {"center_x" : .5, "center_y" : .375}
                    size_hint: .75, .055
                    text: root.password_input
                    on_focus: root.clear_password(self)
                    write_tab: False
                    multiline: False
                    text_validate_unfocus: False
                    on_text_validate: root.password_input = password.text


                Button:
                    id: submit
                    pos_hint: {"center_x" : .35, "center_y" : .125}
                    size_hint: .26, .1
                    background_normal: ""
                    background_color: hex("#296ead")
                    text: "LOG IN"
                    on_press:
                        root.validate(password.text, username.text)
                        root.manager.transition.direction = 'down'
                        if root.state_valid_user: root.manager.current = "list_view"
                        if root.state_invalid_username: invalid_name_label.opacity = 1
                        if root.state_invalid_password: invalid_password_label.opacity = 1
                Button:
                    id: new_user
                    pos_hint: {"center_x" : .65, "center_y" : .125}
                    size_hint: .26, .1
                    background_normal: ""
                    background_color: hex("#931858")
                    text: "NEW USER"
                    on_press:
                        submit.text: "Add User"
                        root.state_no_users = True
                        root.new_user_entry()

        BoxLayout:
            size_hint: .05, 1

<AddTaskScreen>:
    name: "add_task"

<ListViewScreen>:
    name: "list_view"
    on_pre_leave:
        root.manager.update_selected_task(root.selected_task)
    on_enter:
        root.current_user = root.manager.current_user
        root.init_user_tasks()
    canvas.before:
        Rectangle:
            size: self.size
            source: "resources/images/5039684.jpg"

<ViewTaskScreen>:
    on_pre_enter:
        root.selected_task = root.manager.pass_selected_task()
    on_enter:
        root.generate_text()
    on_leave:
        root.selected_task = None
        root.task_text = ""
    name: "view_task"
    canvas.before:
        Rectangle:
            size: self.size
            source: "resources/images/5039684.jpg"
    RelativeLayout:
        Label:
            pos_hint: {"center_x" : .5, "center_y" : .425}
            size_hint: 1, .9
            text: root.task_text
        Button:
            id: back
            pos_hint: {"center_x" : .5, "center_y" : .15}
            size_hint: .4, .1
            background_normal: ""
            background_color: hex("#296ead")
            text: "Back"
            on_press:
                root.manager.current = "list_view"
                root.manager.transition.direction = "down"


<TaskButton>:
    on_press:
        root.parent.parent.parent.manager.transition.direction = 'up'
        root.parent.parent.parent.open_task_window(self.text)
        root.parent.parent.parent.manager.selected_task = root.parent.parent.parent.selected_task
        root.parent.parent.parent.manager.current = "view_task"